spring:
  application:
    name: multiple-users

data-sources:
  - name: data-base-1
    strategy: postgres
    url: jdbc:postgresql://localhost:5432/dataSource1
    table: users
    user: user
    password: pass
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
  - name: data-base-2
    strategy: postgres
    url: jdbc:postgresql://localhost:5433/dataSource2
    table: user_table
    user: user
    password: pass
    mapping:
      id: ldap_login
      username: ldap_login
      name: name
      surname: surname